version: '3.8'

services:
  web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.schedule-web.rule=Host(`schedule.vingp.dev`)"
      - "traefik.http.routers.schedule-web.entrypoints=http,https"
      - "traefik.http.routers.schedule-web.tls.certresolver=myresolver"
      - "traefik.http.services.schedule-web.loadbalancer.server.port=3000"

    networks:
      - traefik

networks:
  traefik:
    external: true
